python3-oletools: don't use pip/wheel in checkdepends.
python3-pip was necessary because the 'python3 setup.py test' command
was trying to install the oletools package itself:

    error: Command '['/usr/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpjxhh802n', '--quiet', 'oletools>=0.54']' returned non-zero exit status 1.

Switching to pytest as the test runner fixes this.